AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - '.git/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'spec/*_helper.rb'
    - !ruby/regexp /old_and_unused\.rb$/

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 90

