language: ruby
rvm:
  - 2.2.3
env:
  - DB=postgresql
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rake db:migrate RAILS_ENV=test --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
  - rackup private_pub.ru -s puma -E production -p 9292
addons:
  code_climate:
    repo_token: a49b814d672ed9d6313fb8f2619ea7b631c28d37454a0b6ae234988b49fc635e

