language: ruby
rvm:
  - 2.2.3
env:
  - DB=postgresql
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rake db:migrate RAILS_ENV=test --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

